/**
 * Interactive setup wizard.
 *
 * Walks the user through:
 *   1. Telegram bot token
 *   2. Authorized TG user IDs
 *   3. Helius API key (and derives HELIUS_RPC_URL)
 *   4. Webhook public URL (or skip for poll mode)
 *   5. Database URL (defaults to a local docker-compose Postgres)
 *
 * Writes .env, then runs the SQL schema from sql/001_init.sql.
 *
 * Pure-function validators live in ./validate so the wizard stays testable
 * without mocking prompts.
 */
import fs from "node:fs";
import path from "node:path";
import { randomBytes } from "node:crypto";
import prompts from "prompts";
import {
  validateTelegramToken,
  validateHeliusKey,
  validateTgUserList,
  generateWebhookSecret,
} from "./validate.js";

interface SetupEnv {
  TELEGRAM_BOT_TOKEN: string;
  AUTHORIZED_TG_USERS: string;
  HELIUS_RPC_URL: string;
  HELIUS_WEBHOOK_SECRET: string;
  WEBHOOK_PUBLIC_URL: string;
  DATABASE_URL: string;
  B402_CLUSTER: string;
  MASTER_SEED: string;
}

export async function runSetupWizard(): Promise<void> {
  // eslint-disable-next-line no-console
  console.log("stealth-trader setup");
  // eslint-disable-next-line no-console
  console.log("Press Ctrl-C at any prompt to abort. Nothing is written until the end.\n");

  const env: Partial<SetupEnv> = {
    B402_CLUSTER: "mainnet",
    // Empty = zero-Docker pglite default at ~/.stealth-trader/db.
    // Set to postgresql://... only if you want a real cluster.
    DATABASE_URL: "",
    HELIUS_WEBHOOK_SECRET: generateWebhookSecret(() => randomBytes(32)),
    MASTER_SEED: generateWebhookSecret(() => randomBytes(32)),
  };

  env.TELEGRAM_BOT_TOKEN = await ask(
    "Telegram bot token (from @BotFather)",
    validateTelegramToken,
  );

  env.AUTHORIZED_TG_USERS = await ask(
    "Authorized Telegram user IDs (comma-separated, from @userinfobot)",
    validateTgUserList,
  );

  const heliusKey = await ask("Helius API key (from dev.helius.dev)", validateHeliusKey);
  env.HELIUS_RPC_URL = `https://mainnet.helius-rpc.com/?api-key=${heliusKey}`;

  const webhookUrl = (
    await prompts({
      type: "text",
      name: "v",
      message:
        "Public webhook URL — needed only for /follow copy-trade (use ngrok or your host). " +
        "Leave blank if you only need /buy /sell /cashout /holdings.",
    })
  ).v as string | undefined;
  env.WEBHOOK_PUBLIC_URL = webhookUrl?.trim() ?? "";

  const dbUrl = (
    await prompts({
      type: "text",
      name: "v",
      message:
        "Postgres URL (leave blank to use the zero-Docker pglite default at ~/.stealth-trader/db)",
    })
  ).v as string | undefined;
  if (dbUrl?.trim()) env.DATABASE_URL = dbUrl.trim();

  const envPath = path.resolve(process.cwd(), ".env");
  fs.writeFileSync(envPath, renderEnv(env as SetupEnv));
  // eslint-disable-next-line no-console
  console.log(`\nWrote ${envPath}`);
  // eslint-disable-next-line no-console
  console.log(
    `\nMASTER_SEED was generated for you and stored in .env.\n` +
    `Back this file up — losing it means losing every shielded note your users hold.\n`,
  );
  // eslint-disable-next-line no-console
  console.log(`Advanced (optional): set OPERATOR_FEE_KEYPAIR_PATH to a Solana keypair file`);
  // eslint-disable-next-line no-console
  console.log(`  with ~0.05 SOL — it covers one-time recipient ATA rent on /cashout so users`);
  // eslint-disable-next-line no-console
  console.log(`  never see "insufficient funds for rent" the first time they withdraw.\n`);
  // eslint-disable-next-line no-console
  console.log("Next: pnpm start  (schema auto-applies on first boot)");
}

async function ask<T>(
  message: string,
  validate: (s: string) => { ok: true; value: T } | { ok: false; error: string },
): Promise<T> {
  // Loop until valid or the user aborts (Ctrl-C). prompts returns undefined on abort.
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const r = await prompts({ type: "text", name: "v", message });
    const raw = (r.v as string | undefined) ?? "";
    if (!raw && r.v === undefined) {
      throw new Error("aborted");
    }
    const v = validate(raw);
    if (v.ok) return v.value;
    // eslint-disable-next-line no-console
    console.error(`  ${v.error}`);
  }
}

function renderEnv(env: SetupEnv): string {
  return [
    "# stealth-trader — generated by setup wizard",
    "# MASTER_SEED is the root of every user's wallet. Back it up offline.",
    `TELEGRAM_BOT_TOKEN=${env.TELEGRAM_BOT_TOKEN}`,
    `AUTHORIZED_TG_USERS=${env.AUTHORIZED_TG_USERS}`,
    `HELIUS_RPC_URL=${env.HELIUS_RPC_URL}`,
    `HELIUS_WEBHOOK_SECRET=${env.HELIUS_WEBHOOK_SECRET}`,
    `WEBHOOK_PUBLIC_URL=${env.WEBHOOK_PUBLIC_URL}`,
    `DATABASE_URL=${env.DATABASE_URL}`,
    `B402_CLUSTER=${env.B402_CLUSTER}`,
    `MASTER_SEED=${env.MASTER_SEED}`,
    "",
  ].join("\n");
}
